import { Decimal, d } from "./decimal.js";

export interface ChartSeries {
  label: string;
  points: { x: string; y: number }[];
}

/** Render an ASCII sparkline from numbers. */
export function sparkline(values: number[], width = 40): string {
  if (values.length === 0) return "";
  const ticks = "▁▂▃▄▅▆▇█";
  const data = values.slice(-width);
  const min = Math.min(...data);
  const max = Math.max(...data);
  const range = max - min || 1;
  return data
    .map((v) => ticks[Math.min(7, Math.floor(((v - min) / range) * 8))])
    .join("");
}

/** Render a simple terminal bar chart. */
export function barChart(items: { label: string; value: number }[], maxBarWidth = 30): string {
  if (items.length === 0) return "";
  const maxVal = Math.max(...items.map((i) => Math.abs(i.value))) || 1;
  const maxLabel = Math.max(...items.map((i) => i.label.length));
  return items
    .map((item) => {
      const width = Math.round((Math.abs(item.value) / maxVal) * maxBarWidth);
      const bar = "█".repeat(width);
      return `${item.label.padEnd(maxLabel)}  ${bar} ${item.value.toFixed(2)}`;
    })
    .join("\n");
}

/**
 * Generate a self-contained HTML report with inline SVG charts.
 * No external dependencies — opens in any browser.
 */
export function htmlReport(title: string, sections: ReportSection[]): string {
  const sectionHtml = sections
    .map((s) => {
      let content = "";
      if (s.table) {
        content += `<table><thead><tr>${s.table.headers.map((h) => `<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>`;
        content += s.table.rows.map((r) => `<tr>${r.map((c) => `<td>${esc(c)}</td>`).join("")}</tr>`).join("");
        content += `</tbody></table>`;
      }
      if (s.chart) {
        content += svgChart(s.chart);
      }
      if (s.text) {
        content += `<p>${esc(s.text).replace(/\n/g, "<br>")}</p>`;
      }
      return `<section><h2>${esc(s.heading)}</h2>${content}</section>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
body{font-family:system-ui,sans-serif;background:#0f1117;color:#e2e4e9;max-width:900px;margin:0 auto;padding:24px}
h1{color:#5b9cf5;font-size:20px}h2{color:#8b8fa3;font-size:15px;margin-top:28px}
table{border-collapse:collapse;width:100%;margin:12px 0;font-size:13px}
th,td{padding:6px 10px;border:1px solid #2a2e3a;text-align:left}
th{color:#8b8fa3}svg{margin:12px 0}p{font-size:13px;line-height:1.6}
.footer{color:#555;font-size:11px;margin-top:40px}
</style></head><body>
<h1>${esc(title)}</h1>
${sectionHtml}
<div class="footer">Generated by fin-alfred · ${new Date().toISOString()}</div>
</body></html>`;
}

export interface ReportSection {
  heading: string;
  text?: string;
  table?: { headers: string[]; rows: string[][] };
  chart?: ChartSeries[];
}

function svgChart(series: ChartSeries[], width = 600, height = 200): string {
  const allPoints = series.flatMap((s) => s.points);
  if (allPoints.length === 0) return "";
  const minY = Math.min(...allPoints.map((p) => p.y));
  const maxY = Math.max(...allPoints.map((p) => p.y));
  const rangeY = maxY - minY || 1;
  const colors = ["#5b9cf5", "#4ade80", "#f87171", "#fbbf24"];

  let paths = "";
  series.forEach((s, si) => {
    if (s.points.length < 2) return;
    const coords = s.points.map((p, i) => {
      const x = (i / (s.points.length - 1)) * (width - 60) + 40;
      const y = height - 30 - ((p.y - minY) / rangeY) * (height - 60);
      return `${x.toFixed(1)},${y.toFixed(1)}`;
    });
    paths += `<polyline points="${coords.join(" ")}" fill="none" stroke="${colors[si % colors.length]}" stroke-width="2"/>`;
    paths += `<text x="40" y="${height - 8}" fill="#8b8fa3" font-size="10">${esc(s.label)}</text>`;
  });

  // Y-axis labels
  const yLabels = [minY, (minY + maxY) / 2, maxY]
    .map((v, i) => {
      const y = height - 30 - (i / 2) * (height - 60);
      return `<text x="4" y="${y + 4}" fill="#555" font-size="10">${v.toFixed(1)}</text>`;
    })
    .join("");

  return `<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
<rect width="${width}" height="${height}" fill="#181b23" rx="6"/>
${yLabels}${paths}</svg>`;
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
