import { FormEvent, useEffect, useState } from "react";
import type { AppBridge } from "../bridge/AppBridge";
import type { ProfileActivity } from "../domain/types";

export function ActivityPage({ bridge, profileId, view }: { bridge: AppBridge; profileId: string; view: "组合" | "账本" | "审计" }) {
  const [activity, setActivity] = useState<ProfileActivity>();
  const [error, setError] = useState("");
  const [revision, setRevision] = useState(0);
  useEffect(() => { void bridge.getProfileActivity(profileId).then(setActivity).catch((reason) => setError(reason instanceof Error ? reason.message : String(reason))); }, [bridge, profileId, revision]);
  if (error) return <section className="activity-page"><output>{error}</output></section>;
  if (!activity) return <section className="activity-page">正在读取加密档案…</section>;
  if (view === "组合") return <section className="activity-page"><header><div><p className="eyebrow">当前正式账本</p><h2>组合概览</h2></div></header><div className="portfolio-cards"><div><small>1810.HK持股</small><strong>{Number(activity.ledger.quantity).toLocaleString()}股</strong></div><div><small>HKD现金</small><strong>HK${Number(activity.ledger.cash).toLocaleString()}</strong></div><div><small>正式建议</small><strong>{activity.decisions.length}</strong></div></div><p>卖出所得现金不会自动再部署；任何新增风险都需要独立估值、组合约束和人工审批。</p><CashDeploymentPanel bridge={bridge} /></section>;
  if (view === "账本") return <section className="activity-page"><header><div><p className="eyebrow">只记录真实成交</p><h2>成交账本</h2></div><span>{activity.executions.length}笔</span></header>{activity.ledger.quantity === "0" && activity.ledger.cash === "0" && !activity.executions.length && <LedgerBaselineForm bridge={bridge} profileId={profileId} onChanged={() => setRevision((value) => value + 1)} />}{(activity.ledger.quantity !== "0" || activity.ledger.cash !== "0" || activity.executions.length > 0) && <ManualExecutionForm bridge={bridge} profileId={profileId} onChanged={() => setRevision((value) => value + 1)} />}{activity.executions.length > 0 && <FeeRevisionForm bridge={bridge} profileId={profileId} executions={activity.executions} onChanged={() => setRevision((value) => value + 1)} />}{activity.executions.length ? <div className="table-wrap"><table><thead><tr><th>日期</th><th>方向</th><th>股数</th><th>均价</th><th>总费用</th><th>净现金流</th><th>幂等键</th></tr></thead><tbody>{activity.executions.map((item) => <tr key={item.executionKey}><td>{item.tradedAt}</td><td>{item.side === "sell" ? "卖出" : "买入"}</td><td>{Number(item.quantity).toLocaleString()}</td><td>HK${item.price}</td><td>HK${Number(item.stampDuty) + Number(item.clearingFee) + Number(item.transferFee) + Number(item.commission)}</td><td>HK${Number(item.netCashFlow).toLocaleString()}</td><td><code>{item.executionKey}</code></td></tr>)}</tbody></table></div> : <p>该档案尚无真实成交。</p>}</section>;
  return <section className="activity-page"><header><div><p className="eyebrow">档案级隔离 · Schema v4</p><h2>审计时间线</h2></div><span>{activity.audits.length}项</span></header><div className="audit-list">{activity.audits.map((item) => <article key={item.id}><time>{item.createdAt}</time><strong>{item.aggregateType} · {item.eventType}</strong><code>{item.aggregateId}</code><details><summary>查看结构化载荷</summary><pre>{JSON.stringify(item.payload, null, 2)}</pre></details></article>)}{!activity.audits.length && <p>该档案尚无审计事件。</p>}</div></section>;
}

function LedgerBaselineForm({ bridge, profileId, onChanged }: { bridge: AppBridge; profileId: string; onChanged: () => void }) {
  const [quantity, setQuantity] = useState(""); const [cash, setCash] = useState(""); const [notice, setNotice] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); try { await bridge.initializeLedgerBaseline(profileId, quantity, cash); setNotice("初始持仓与现金已由用户核验并写入审计。基线只能建立一次。"); onChanged(); } catch (error) { setNotice(String(error)); } }
  return <form className="ledger-entry" onSubmit={submit}><h3>建立一次性账本基线</h3><p>适用于新建的家人档案。填写当前实际持股和现金，不会生成历史成交或连接券商。</p><label>1810.HK初始持股<input aria-label="初始持股" inputMode="numeric" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><label>HKD初始现金<input aria-label="初始现金" inputMode="decimal" value={cash} onChange={(event) => setCash(event.target.value)} /></label><button type="submit" disabled={!quantity || !cash}>确认并建立基线</button>{notice && <output>{notice}</output>}</form>;
}

function ManualExecutionForm({ bridge, profileId, onChanged }: { bridge: AppBridge; profileId: string; onChanged: () => void }) {
  const [input, setInput] = useState({ side: "sell" as "buy" | "sell", tradedAt: "", quantity: "", price: "", stampDuty: "0", clearingFee: "0", transferFee: "0", commission: "0", externalId: "" }); const [notice, setNotice] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); try { const result = await bridge.recordManualExecution({ profileId, ...input }); setNotice(result.applied ? `既成成交已原子登记，幂等键 ${result.executionKey}。` : "相同成交已存在，账本未改变。"); onChanged(); } catch (error) { setNotice(String(error)); } }
  return <form className="ledger-entry" onSubmit={submit}><h3>登记既成券商成交</h3><p>这里不会下单。请只登记已经在券商成交的结果；外部成交编号可增强去重稳定性。</p><label>方向<select aria-label="成交方向" value={input.side} onChange={(event) => setInput((value) => ({ ...value, side: event.target.value as "buy" | "sell" }))}><option value="sell">卖出</option><option value="buy">买入</option></select></label><label>日期<input aria-label="手工成交日期" type="date" value={input.tradedAt} onChange={(event) => setInput((value) => ({ ...value, tradedAt: event.target.value }))} /></label><label>股数<input aria-label="手工成交股数" value={input.quantity} onChange={(event) => setInput((value) => ({ ...value, quantity: event.target.value }))} /></label><label>均价<input aria-label="手工成交均价" value={input.price} onChange={(event) => setInput((value) => ({ ...value, price: event.target.value }))} /></label>{([['stampDuty','印花税'],['clearingFee','清算费'],['transferFee','过户费'],['commission','手续费']] as const).map(([key, label]) => <label key={key}>{label}<input aria-label={`手工${label}`} value={input[key]} onChange={(event) => setInput((value) => ({ ...value, [key]: event.target.value }))} /></label>)}<label>券商成交编号<input aria-label="手工券商成交编号" value={input.externalId} onChange={(event) => setInput((value) => ({ ...value, externalId: event.target.value }))} /></label><button type="submit" disabled={!input.tradedAt || !input.quantity || !input.price}>登记既成成交</button>{notice && <output>{notice}</output>}</form>;
}

function FeeRevisionForm({ bridge, profileId, executions, onChanged }: { bridge: AppBridge; profileId: string; executions: ProfileActivity["executions"]; onChanged: () => void }) {
  const first = executions[0]; const [executionKey, setExecutionKey] = useState(first.executionKey); const [fees, setFees] = useState({ stampDuty: first.stampDuty, clearingFee: first.clearingFee, transferFee: first.transferFee, commission: first.commission }); const [notice, setNotice] = useState("");
  function select(key: string) { setExecutionKey(key); const item = executions.find((candidate) => candidate.executionKey === key); if (item) setFees({ stampDuty: item.stampDuty, clearingFee: item.clearingFee, transferFee: item.transferFee, commission: item.commission }); }
  async function submit(event: FormEvent) { event.preventDefault(); try { const result = await bridge.reviseExecutionFees(profileId, executionKey, fees); setNotice(result.applied ? `费用已原子修订；成交身份与持股不变，现金更新为 HK$${result.cash}。` : "费用未变化，本次为 no-op。"); onChanged(); } catch (error) { setNotice(String(error)); } }
  return <form className="ledger-entry" onSubmit={submit}><h3>修订成交费用</h3><p>不会新增或重放成交，只按费用差额调整现金，并保留同一幂等键和完整审计。</p><label>成交<select aria-label="待修订成交" value={executionKey} onChange={(event) => select(event.target.value)}>{executions.map((item) => <option key={item.executionKey} value={item.executionKey}>{item.tradedAt} · {item.side} · {item.quantity}股</option>)}</select></label>{([['stampDuty','修订印花税'],['clearingFee','修订清算费'],['transferFee','修订过户费'],['commission','修订手续费']] as const).map(([key, label]) => <label key={key}>{label}<input aria-label={label} value={fees[key]} onChange={(event) => setFees((value) => ({ ...value, [key]: event.target.value }))} /></label>)}<button type="submit">保存费用修订</button>{notice && <output>{notice}</output>}</form>;
}

function CashDeploymentPanel({ bridge }: { bridge: AppBridge }) {
  const [input, setInput] = useState({ red_line_clear: false, evidence_complete: false, valuation_current: false, expected_irr: "", bear_downside: "", balance_sheet_safe: false, liquidity_reserve_met: false, resulting_single_name_weight: "" });
  const [result, setResult] = useState<{ canDeploy: boolean; failedChecks: string[] }>();
  return <section className="cash-deployment"><h3>卖出现金再部署边界</h3><p>这里只评估是否允许进入“新增风险审批”，不会自动买入或预留资金。</p><div>{([['red_line_clear','红线全部Clear'],['evidence_complete','证据完整'],['valuation_current','估值仍有效'],['balance_sheet_safe','资产负债表安全'],['liquidity_reserve_met','流动性储备满足']] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={input[key]} onChange={(event) => setInput((value) => ({ ...value, [key]: event.target.checked }))} />{label}</label>)}</div><label>预期IRR（百分数）<input aria-label="再部署预期IRR" value={input.expected_irr} onChange={(event) => setInput((value) => ({ ...value, expected_irr: event.target.value }))} /></label><label>Bear下行（百分数）<input aria-label="再部署Bear下行" value={input.bear_downside} onChange={(event) => setInput((value) => ({ ...value, bear_downside: event.target.value }))} /></label><label>部署后单股仓位（百分数）<input aria-label="部署后单股仓位" value={input.resulting_single_name_weight} onChange={(event) => setInput((value) => ({ ...value, resulting_single_name_weight: event.target.value }))} /></label><button type="button" disabled={!input.expected_irr || !input.bear_downside || !input.resulting_single_name_weight} onClick={async () => setResult(await bridge.evaluateCashDeployment(input))}>评估再部署边界</button>{result && <output>{result.canDeploy ? "所有硬门槛通过；仍需单独人工审批，系统不会下单。" : `禁止再部署：${result.failedChecks.join("、")}`}</output>}</section>;
}
